services:

  ####################################################################################################
  # PHP
  ####################################################################################################
  php:
    build: .docker/php
    ports:
      - 1000:5173
    volumes:
      - .:/var/www:cached
    networks:
      - dasignet

  ####################################################################################################
  # Nginx
  ####################################################################################################
  nginx:
    image: nginx
    ports:
      - 1001:80
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    environment:
      - APP_NAME=DasigLocal
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:SarxdSSGGWIlA5EDolCkrDvpy4qwA7DBMG5A9XNwv5w=
      - DB_CONNECTION=mysql
      - DB_DRIVER=Pdo
      - DB_HOST=database
      - DB_PASSWORD=Qwsxza123!@#
      - DB_USERNAME=dasig
      - DB_DATABASE=dasig_db
    networks:
      - dasignet

  ####################################################################################################
  # DATABASE (MySQL)
  ####################################################################################################
  database:
    image: mysql:8.1
    ports:
      - 3306:3306
    volumes:
      - .docker/db/data:/var/lib/mysql
      - .docker/logs:/var/log/mysql
      - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - .docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=Qwsxza123!@#
      - MYSQL_PASSWORD=Qwsxza123!@#
      - MYSQL_DATABASE=dasig_db
      - MYSQL_USER=dasig
      - MYSQL_ROOT_HOST=%
      - MYSQL_INITDB_SKIP_TZINFO=yes
      - MYSQL_SQL_MODE=
    networks:
      - dasignet

  ####################################################################################################
  # Adminer
  ####################################################################################################
  adminer:
    image: adminer
    ports:
      - 1002:8080
    depends_on:
      - database
    networks:
      - dasignet

  ####################################################################################################
  # Redis
  ####################################################################################################
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - .docker/redis/data:/data
    ports:
      - 6380:6379
    networks:
      - dasignet

  # ####################################################################################################
  # # DATABASE (MariaDB)
  # ####################################################################################################
  # db:
  #     image: mariadb:10.11
  #     ports:
  #         - 3306:3306
  #     volumes:
  #         - .docker/db/data:/var/lib/mysql
  #         - .docker/logs:/var/log/mysql
  #         - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
  #         - .docker/db/sql:/docker-entrypoint-initdb.d
  #     environment:
  #         MYSQL_ROOT_PASSWORD: root
  #         MYSQL_DATABASE: laravel_db_name
  #         MYSQL_USER: laravel_db_user
  #         MYSQL_PASSWORD: laravel_db_pass

  ####################################################################################################
  # PostgreSQL
  ####################################################################################################
  # db:
  #     image: postgres:16
  #     ports:
  #         - 5432:5432
  #     volumes:
  #         - .docker/db/data:/var/lib/postgresql/data
  #         - .docker/db/sql:/docker-entrypoint-initdb.d
  #     environment:
  #         - POSTGRES_USER=refactorian
  #         - POSTGRES_PASSWORD=refactorian
  #         - POSTGRES_DB=refactorian

  ####################################################################################################
  # pgAdmin
  ####################################################################################################
  # pgadmin:
  #     image: dpage/pgadmin4
  #     ports:
  #         - 5050:80
  #     environment:
  #         - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #         - PGADMIN_DEFAULT_PASSWORD=password
  #     depends_on:
  #         - db

networks:
  dasignet:
    external: true
